[build-system]
requires = ["maturin>=0.13,<0.14"]
build-backend = "maturin"

[project]
name = "pyo3-mixed-include-exclude"
classifiers = ["Programming Language :: Python", "Programming Language :: Rust"]
requires-python = ">=3.7"
dependencies = ["boltons"]

[project.scripts]
get_42 = "pyo3_mixed_include_exclude:get_42"

[tool.maturin]
include = ["include_this_file", "missing"]
exclude = ["exclude_this_file", "tests/**/*", ".gitignore", "unused"]
