[package]
authors = ["konstin <konstin@mailbox.org>"]
name = "pyo3-mixed-submodule"
version = "2.1.3"
description = "Implements a dummy function combining rust and python"
readme = "Readme.md"
edition = "2021"

[package.metadata.maturin]
name = "pyo3_mixed_submodule.rust_module.rust"

[dependencies]
pyo3 = { version = "0.15.1", features = ["extension-module"] }

[lib]
name = "pyo3_mixed_submodule"
crate-type = ["cdylib"]
