[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[project]
name = "pyo3-mixed-submodule"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Rust"
]
