# This configuration is not great but it suffices to publish wheels for maturin for 64-bit arm (aarch64)

kind: pipeline
type: docker
name: linux_aarch64
platform:
  arch: arm64

steps:
- name: publish
  image: python:3.8-buster
  environment:
    PATH: "/root/.local/bin:/root/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    MATURIN_PASSWORD:
      from_secret: MATURIN_PASSWORD
  commands:
    - curl https://sh.rustup.rs -sSf | sh -s -- --profile minimal -y
    - rustup target add aarch64-unknown-linux-musl
    - cargo build --release --target aarch64-unknown-linux-musl
    - cargo run --release --target aarch64-unknown-linux-musl -- publish -u konstin -b bin --no-sdist --target aarch64-unknown-linux-musl
  when:
    event:
      - tag