repos:
  - repo: local
    hooks:
      # rustup component add rustfmt
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all --
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-check
        name: cargo check
        entry: cargo check --all-features --all-targets --
        language: system
        pass_filenames: false
        types: [rust]
      # cargo install --locked cargo-deny
      - id: cargo-deny
        name: cargo deny
        entry: cargo deny --all-features check --
        language: system
        pass_filenames: false
      # rustup component add clippy
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --tests --all-features -- -D warnings
        language: system
        pass_filenames: false
        types: [rust]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
        exclude: |
          (?x)(
              (^sysconfig/)|
              (.*\.stdout)
          )
      - id: trailing-whitespace
        exclude: |
          (?x)(
              (^sysconfig/)|
              (.*\.stdout)
          )
      - id: mixed-line-ending
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.287
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        entry: mypy maturin/
        pass_filenames: false
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
    - id: codespell
