[build]
  publish = "guide/book/"
  command = "curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.23/mdbook-v0.4.23-x86_64-unknown-linux-musl.tar.gz | tar xvz && ./mdbook build guide"
