[package]
name = "pyo3-ffi-pure"
version = "1.0.0"
edition = "2018"

[dependencies]
pyo3-ffi = { git = "https://github.com/PyO3/pyo3.git", branch = "main", features = ["extension-module"] }

[lib]
name = "pyo3_ffi_pure"
crate-type = ["cdylib"]
