[package]
name = "cargo-mock"
version = "0.1.0"
authors = ["konstin <konstin@mailbox.org>"]
edition = "2018"

[[bin]]
name = "cargo"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.28"
cargo_metadata = "0.11.4"
serde_json = "1.0.53"
