[package]
authors = ["konstin <konstin@mailbox.org>"]
name = "pyo3-mixed"
version = "2.1.3"
description = "Implements a dummy function combining rust and python"
edition = "2018"

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module", "generate-import-lib"] }

[lib]
name = "pyo3_mixed"
crate-type = ["cdylib"]
