[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[tool.maturin]
bindings = "bin"

[[tool.maturin.targets]]
name = "hello-world"
bindings = "bin"

[[tool.maturin.targets]]
name = "foo"
