[profile.default]
# Terminate slow tests after 5 minutes
slow-timeout = { period = "60s", terminate-after = 5 }

[[profile.default.overrides]]
# See https://nexte.st/book/threads-required.html
filter = 'test(/_uniffi_/)'
threads-required = "num-cpus"